---
title: Project Proposal Paper
authors:
  - name: Eleanor Lindsey
    affiliation: Colorado State University
    roles: writing
    corresponding: True
  - name: Clara Jordan 
    affiliation: Colorado State University
    roles: writing
    corresponding: False
  - name: Sierra Champion
    affiliation: Colorado State University
    roles: writing
    corresponding: False
bibliography: references.bib
---

## Project Proposal Idea #1-Eleanor

Title: The state of Eutrophication at Horsetooth Reservoir

This topic is important because as climate change makes an impact on the amount of precipitation we see here in Colorado, our streams and local reservoirs will feel the impact[@assessment2016upper]. The water being held in Horsetooth is used as a spot of recreation as well as a source for agriculture and industrial use[@gelder2003eutrophication].

Hypothesis:

How has climate change impacted the state of eutrophication at Horsetooth over the last 5 years?

we expect that the state of eutrophication will increase as inputs are decreased and temperatures increase.

Methods:

Looking at data pulled from USGS from the last 5 years, create an analysis of trends in precipitation, stream discharge, dissolved oxygen, and temperature to discuss changes in stream inputs and outputs. Using the data create a report about the state of Eutrophication of Horsetooth Reservoir.

Outcome:

Based on the outcome we would expect to see a decrease in inputs which would have some effect on the nutrient load within Horsetooth. The increase in residence time, coupled with a decrease in inputs, would lead to an expected increase in eutrophication.

Resources:

Using USGS water quality data as the main source[@horsetoothData].

## Project Proposal Idea #2-Eleanor

Title: Change in temperature within the city of Denver as population increases

The heat island effect which states that as infrastructure increases in comparison to green space, the average temperature of the areas will increase. This happens because the green space helps monitor moisture in an area. When you remove green areas and put in more concrete and black top you reduce the moisture content leading to a hot, dry city. You can use population data to gauge how developed a city is over time. As climate change is perpetuated, cities will become hotter which leads to dangerous circumstances for those who live within the city.

Hypothesis:

With the increase in population, the temperature will increase as well.

Methods:

Using temperature records from USGS[@denvertemp] coupled with population data we will analyze the change in population within the city of Denver to see the determined effect on rising temperatures[@DenverPop].

Outcome:

How has the increase in population within Denver, Colorado impacted the heat island effect?

Resources:

Census report on population change over time. us climate data report on temperatures in Denver

## Project Proposal Idea#1-Sierra

Title: How Tree Canopy Affects Urban Heat and Inequality

Justification: Cities are usually hotter than the areas around them because of the urban heat island (UHI) effect. This happens when buildings, roads, and other hard surfaces soak up and hold heat, especially when few trees or green spaces are around. Tree cover helps cool things down by providing shade and lowering surface and air temperatures. However, not all neighborhoods have the same tree canopy. Lower-income and marginalized communities often have fewer trees and more heat exposure [@UrbanHeat. That means these communities are more vulnerable to heat-related health issues and less prepared for climate impacts. By looking at how tree canopy relates to temperature and demographics, we can better understand these patterns and push for equal urban planning and climate solutions [@TreeCanopy]\].

Research Objective / Hypothesis: We want to find out if areas with more tree canopy are cooler, and if low-income or minority neighborhoods tend to have less tree cover.

Hypothesis: More tree canopy means lower surface temperatures, but the benefits are not shared equally across different socioeconomic groups.

Proposed Methods: We will use MODIS satellite data to get surface temperature and tree canopy data from the U.S. Forest Service’s Urban FIA or local city GIS data. For demographic data (like income and race), we will use the U.S. Census Bureau’s American Community Survey (ACS). We will pick one city to focus on and look at trends over the past 5-10 years. In RStudio, we will run correlation and regression analyses to see how tree canopy, temperature, and demographics are related. We will also use ggplot2 and tidyverse tools to make maps and graphs.

Expected Outcomes: We expect that more tree cover leads to cooler surface temperatures, but disadvantaged neighborhoods often do not get as much of that benefit. These results support more equitable tree-planting and greening projects in cities.

## Project Proposal Idea#2-Sierra

Title: How Rising Temperatures Are Impacting Corn and Soybean Yields in the Midwest

Justification: Midwestern agriculture depends heavily on stable weather, but with climate change, farmers are already dealing with hotter temperatures, less predictable rainfall, and more extreme weather. These changes are especially tough on crops like corn and soybeans, which are significant parts of the region’s economy [@Climatetrends]. Heat during the growing season can hurt plant growth and lower yields, especially during sensitive periods like pollination [@Tempextremes]. This project aims to figure out how climate trends have affected these crops and what that means for the future of farming in the Midwest.

Research Objective / Hypothesis: Our goal is to explore how rising temperatures and changes in precipitation have affected corn and soybean yields in Iowa, Illinois, and Indiana over the past 20+ years.

Hypothesis: Hotter summers, especially extreme heat during June through August, are linked to lower crop yields, while steady rainfall has a more positive effect.

Proposed Methods: We will get temperature and rainfall data from NOAA and crop yield data from the USDA’s National Agricultural Statistics Service. The study will cover the years 2000 to 2023. We will clean and organize the data in R, then use time series analysis and linear regression to see how climate variables and crop yields relate. To test our hypothesis, we will also use ggplot2 to make visualizations.

Expected Outcomes: The results will likely show that high temperatures, especially heat waves, hurt crop yields, while consistent rainfall helps. This kind of analysis can help farmers and policymakers prepare for climate change and make more informed decisions about agriculture in the region.

## Project Proposal Idea #1-Clara

Title: Climate Change Impacts on the United States Population

 

Justification: It is important to examine how the United States population intersects with the effects of climate change. Using data for climate change from Awesome Public Datasets [@USClimateChange]and US Census Data [@USCensusData] population data we can examine which areas of the US are most at risk for climate change impacts and how many people will be impacted.

 

Research objective/question/hypothesis: Which populations of the United States will be most impacted by climate change?

 

Proposed Methods: To investigate this question I would join these two datasets by their "fips" identifiers. I would then use a linear model to test the relationship between temperature change and state population. I would also take a closer look at which states have had the most temperature and precipitation change using tibbles.

 

Expected Outcomes: I expect to find that heavily populated states and cities will have exacerbated temperature increases due to the urban heat island effect. Additionally, I do not expect there to be more correlations but it will be interesting to see which US populations are experiencing the most significant effects so far.

## Project Proposal Idea #2-Clara

Title: Salmon in Oregon Rivers

 

Justification: Oregon has recently removed major dams [@DamRemoval] and this is impacting salmon conservation efforts. I want to explore the intersection of dams and water quality [@OregonStreams]and salmon populations in Oregon rivers[@meengs2005estimating]because salmon are an important species to conserve and are impacted by human aquatic infrastructure.

 

Research objective/question/hypothesis: I hypothesize that as water quality improves in Oregon river systems that there will be an increase in salmon runs in these river systems.

 

Proposed Methods: To explore this hypothesis I will use a linear regression model to analyze the relationship between river water quality and salmon runs.

 

Expected Outcomes: I expect to find that better water quality results will stem from rivers without dams or recent dam removals, and that this in turn will lead to increased salmon runs. I think salmon runs will increase in these conditions because aquatic species tend to thrive in better water conditions and will thrive in river systems where their migration is not impacted by infrastructure (such as dams).
